Move in message marshalling functions from 'envelopespec' package.
dogmatiq/marshalkit pull request #47
Opened 2020-12-10 06:38 UTC by danilvpetrov

#### What change does this introduce?

This PR moves the message marshalling functions from [`dogmatiq/envelopespec`](https://github.com/dogmatiq/envelopspec) package into this repository.  

#### What issues does this relate to?

Fixes https://github.com/dogmatiq/marshalkit/issues/40.

#### Why make this change?

This change is required to relocate message marshalling functions to the current repository from [`dogmatiq/envelopespec`](https://github.com/dogmatiq/envelopspec) package as they are not related to the envelope spec definitions, but to message marshalling. 

#### Is there anything you are unsure about?

No.

2020-12-10 06:57 UTC, danilvpetrov commented
I had to slightly modify the imports in `envelope_test.go` file compared to what it was before in the [`dogmatiq/envelopespec`](https://github.com/dogmatiq/envelopespec) package as there is a conflict with the `marshalkit.Marshaler` type and `marhalkit/fixtures.Marshaler` variable in the tests.

2020-12-10 23:24 UTC, jmalloc commented
Should we wait until `envelopespec` has been moved/merged/tagged in `interopspec` before merging this?

2020-12-10 23:26 UTC, danilvpetrov commented
Yeah we probably should as the imports and refs would have to be changed.

2020-12-20 08:06 UTC, jmalloc requested changes

2020-12-20 08:06 UTC, jmalloc commented on envelope.go
> +// MustMarshalMessageIntoEnvelope marshals a Dogma message into an envelope.
```suggestion
// MustMarshalMessageIntoEnvelope marshals a Dogma message into an envelopespec.Envelope.
```

2020-12-20 08:06 UTC, jmalloc commented on envelope.go
> +// UnmarshalMessageFromEnvelope unmarshals a Dogma message from an envelope.
```suggestion
// UnmarshalMessageFromEnvelope unmarshals a Dogma message from an envelopespec.Envelope
```

2020-12-20 08:06 UTC, jmalloc commented on envelope.go
> +// representation, as used within message envelopes.
```suggestion
// representation, as used within envelopespec.Envelope.
```

2020-12-20 08:06 UTC, jmalloc commented on envelope.go
> +// representation, as used within message envelopes.
```suggestion
// representation, as used within envelopespec.Envelope.
```

2020-12-20 08:06 UTC, jmalloc commented on envelope.go
> +// within envelopes.
```suggestion
// within envelopespec.Envelope.
```

2020-12-20 08:06 UTC, jmalloc commented on envelope.go
> +// used within envelopes.
```suggestion
// used within envelopespec.Envelope.
```

2020-12-20 08:06 UTC, koden-km requested changes

2020-12-20 08:06 UTC, koden-km commented on envelope.go
> +// UnmarshalEnvelopeTime unmarshals a t from its RFC-3339 representation, as
```suggestion
// UnmarshalEnvelopeTime unmarshals t from its RFC-3339 representation, as
```

2020-12-20 08:06 UTC, koden-km commented on envelope_test.go
> +var _ = Describe("func MarshalMessage()", func() {
```suggestion
var _ = Describe("func MustMarshalMessageIntoEnvelope()", func() {
```

2020-12-20 08:06 UTC, koden-km commented on envelope_test.go
> +var _ = Describe("func UnmarshalMessage()", func() {
```suggestion
var _ = Describe("func UnmarshalMessageFromEnvelope()", func() {
```

2020-12-20 08:06 UTC, koden-km commented on envelope_test.go
> +var _ = Describe("func MarshalIdentity()", func() {
```suggestion
var _ = Describe("func MustMarshalEnvelopeIdentity()", func() {
```

2020-12-20 08:06 UTC, koden-km commented on envelope_test.go
> +var _ = Describe("func UnmarshalIdentity()", func() {
```suggestion
var _ = Describe("func UnmarshalEnvelopeIdentity()", func() {
```

2020-12-20 08:06 UTC, koden-km commented on envelope_test.go
> +var _ = Describe("func MarshalTime()", func() {
```suggestion
var _ = Describe("func MustMarshalEnvelopeTime()", func() {
```

2020-12-20 08:06 UTC, koden-km commented on envelope_test.go
> +var _ = Describe("func UnmarshalTime()", func() {
```suggestion
var _ = Describe("func UnmarshalEnvelopeTime()", func() {
```

2020-12-20 08:07 UTC, danilvpetrov commented on envelope.go
> +// UnmarshalEnvelopeTime unmarshals a t from its RFC-3339 representation, as
```suggestion
// UnmarshalEnvelopeTime unmarshals t from its RFC-3339 representation, as
```

2020-12-20 23:08 UTC, danilvpetrov reviewed
Leaving a comment so I can commit my own suggestion 😄

2020-12-20 23:35 UTC, jmalloc approved these changes

2020-12-21 01:38 UTC, danilvpetrov commented
Sorry @koden-km I am merging this PR in, LMK if you have some comments later on.

2020-12-21 01:38 UTC, merged